// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package titandice

import "fmt"

// Version generated by a particular perso firmware version
// and Titan firmware.
type SignatureVersion uint32

type SignaturePurpose uint32

type SigExtensionHeaderType uint8

const (
	SigHeaderVersion0 SignatureVersion = 0
	SigHeaderversion1 SignatureVersion = 1

	SigFirmware         SignaturePurpose = 0
	SigArchKeyCert      SignaturePurpose = 1
	SigArchKeyCertReq   SignaturePurpose = 2
	SigUserKeyCert      SignaturePurpose = 3
	SiguserKeyCertReq   SignaturePurpose = 4
	SigPrivCmd          SignaturePurpose = 5
	SigSignedRsp        SignaturePurpose = 6
	SigSecureLog        SignaturePurpose = 7
	SigFirmwareID       SignaturePurpose = 8
	SigDeviceIDCert     SignaturePurpose = 9
	SigDeviceIDCSR      SignaturePurpose = 10
	SigAliasKeyCert     SignaturePurpose = 11
	SigArchKeyCertReqV2 SignaturePurpose = 12

	SigExtensionHeaderTypeNone         SigExtensionHeaderType = 0
	_                                  SigExtensionHeaderType = 1 // reserved
	SigExtensionHeaderTypeFirmwareHash SigExtensionHeaderType = 2
)

type KeyType uint8

const (
	_                                 KeyType = 0 // reserved
	_                                 KeyType = 1 // reserved
	_                                 KeyType = 2 // reserved
	_                                 KeyType = 3 // reserved
	_                                 KeyType = 4 // reserved
	KeyTypeDeviceID                   KeyType = 5
	KeyTypeAliasKey                   KeyType = 6
	KeyTypeScribeChannelEncryptionKey KeyType = 7
	KeyTypeTPMEK                      KeyType = 8
	KeyTypeAppGeneric                 KeyType = 128
)

func (k KeyType) String() string {
	switch k {
	case KeyTypeDeviceID:
		return "DeviceID"
	case KeyTypeAliasKey:
		return "AliasKey"
	case KeyTypeScribeChannelEncryptionKey:
		return "ScribeChannelEncryptionKey"
	case KeyTypeTPMEK:
		return "TPMEK"
	case KeyTypeAppGeneric:
		return "AppGeneric"
	}
	return fmt.Sprintf("unrecognized KeyType value (0x%0x)", uint8(k))
}

// Key operation.
type KeyOp uint8

// Key algorithm.
type KeyAlg uint8

const (
	// Key operations.
	KeyOpSign    KeyOp = 0
	KeyOpDecrypt KeyOp = 1
	KeyOpDH      KeyOp = 2

	// Key algorithms.
	KeyAlgECDSAP256 KeyAlg = 0
	KeyAlgECIESP256 KeyAlg = 1
	KeyAlgRSA2048   KeyAlg = 2
	KeyAlgRSA3072   KeyAlg = 3
	KeyAlgECDHP256  KeyAlg = 4
)
