// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package titandice

import (
	"errors"
	"math/rand"
	"testing"
	"time"

	"github.com/google/go-tpm/tpm2"
)

var (
	// Key info from test key. Derived from the key material itself.
	devRwSigningKeyInfo KeyInfo = KeyInfo{0x2b, 0xf4, 0x82, 0x25}

	// Test scribe certificates that signed the DeviceIDScribeCertificate
	// and the DeviceIDCertificate defined in the test_certificates.go file
	// as part of the defaultFEKDICEScribeCertChain. Both certificates were
	// generated by Google internal tools.
	testScribeCert0    []byte = []byte("\x30\x82\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xac\x69\x81\x29\x50\xf6\xec\x55\x12\x7c\xb5\xfd\x17\x45\xd5\x50\xd6\x8d\xfb\x3d\x59\x7b\x8f\x81\xe7\x63\x61\xfb\x86\x45\xc3\x91\xaf\xdd\x46\x87\x60\x45\x15\x30\xa3\x23\x58\x88\x55\x4a\x75\x0b\x15\xc6\x2a\xc1\x68\xcb\xfd\x74\x74\x37\xad\xed\x56\xbd\x06\x25\xde\x45\xab\x2f\x62\x1c\xfa\x16\x7f\xb7\xca\x02\xb4\x11\x59\xb8\x83\x31\x61\xda\x7f\xb8\x52\x60\x47\x9d\x35\x06\xb8\x99\xba\xd2\x71\xb2\xc0\xa5\xa9\x80\xc5\x5f\x08\x79\x5a\x95\xd8\xd4\x1f\x0a\xfa\xdb\x78\x07\x44\xe1\xd5\x75\xd9\x1c\xa4\x19\x1d\x83\xe1\xae\x5d\xf1\x93\x83\x9b\x26\x3c\xb7\x0e\xe0\xc5\x64\x02\x27\xbe\xb5\x24\xbe\x11\x99\xd5\xd4\x5d\x21\x85\x6d\xec\x8e\xc5\x3c\x68\xd2\xeb\x80\xcf\x4f\x96\xd9\x22\x73\x8e\x92\x13\xa5\x80\x07\xd0\x92\x4d\xdd\xce\x03\x01\x06\x88\xfd\xdd\x9d\xd4\xfe\xd2\xfd\xf3\x7b\x8d\x50\x98\x6b\x16\x70\xfd\xa1\x40\x16\xb6\x25\xcf\x95\xc2\x10\x5e\xfc\xd9\x8e\x7a\x2c\x5b\xc5\xf8\xf3\x45\x60\x72\x17\x62\xa8\x91\x44\x13\xf0\x14\xaf\x2e\xbe\x11\x46\xd0\xe7\xd5\x96\xe4\xb6\xe3\x48\xac\x60\x3a\x3d\xb4\x10\x7a\xdc\x96\x48\x98\x64\x39\x15\xb8\xfc\x48\x04\xa0\x56\xa3\x4d\x21\x8e\xb8\x55\x84\x32\xf6\x68\xdd\x6d\xca\x53\xcd\x2f\x97\x56\x89\x55\x5a\x1d\x03\x10\xb6\x83")
	testPayloadKeyCert []byte = []byte("\xef\xf0\x28\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x3d\xb7\x46\x10\x20\xfc\x3e\x3d\xb5\xf5\x79\x43\x61\xba\x79\x6a\x68\x77\x1d\x3e\x43\x4e\x09\xc0\x4b\xdb\xcd\x60\xac\xe3\xd8\x33\x10\x08\x11\xa0\x32\xad\xcc\x61\x47\x94\x9e\x3a\x10\x70\xe3\x08\x67\x42\x13\x1d\xf1\x06\xff\x63\x4c\xa3\x03\x53\x48\x69\x5a\xc0\x38\x4c\xd3\xb0\xd6\xb8\x5c\x64\x89\xc2\x9e\xf5\x26\x6c\x0f\x42\x88\xba\xdd\xf2\x90\x0b\x6f\x32\x9a\x95\xd7\x95\xed\x26\x24\xad\xfb\xf3\x09\x3c\x72\x95\x07\x99\x75\x44\xed\x36\xcb\xb6\xa4\x64\x70\xdb\x3a\x7b\xc7\xad\x59\xd6\xa6\xfc\xe8\x87\xb5\x14\x0d\x57")

	defaultTestCaseOpts *ValidateScribeCertificateChainOptions = &ValidateScribeCertificateChainOptions{
		RwSigningKeyInfos:  []KeyInfo{devRwSigningKeyInfo},
		ScribeCertificates: [][]byte{testScribeCert0, testPayloadKeyCert},
	}
)

func Test_ValidateScribeCertificateChain_Success(t *testing.T) {
	validator, err := NewValidator(defaultTestCaseOpts)
	if err != nil {
		t.Fatalf("NewValidator(%v) failed: %v", defaultTestCaseOpts, err)
	}

	// Only one default scribe cert chain needs to be validated
	// as both cert chains follow the exact same format.
	if err := ValidateScribeCertificateChain(&defaultFEKDICEScribeCertChain, validator); err != nil {
		t.Errorf("ValidateScribeCertificateChain(%v, %v) failed: %v", defaultFEKDICEScribeCertChain, defaultTestCaseOpts, err)
	}
}

func Test_ValidateScribeCertificateChain_Errors(t *testing.T) {
	for _, tc := range []struct {
		name                 string
		certChainPerturbator func(*TitanDiceScribeCertificateChain)
		wantErr              error
	}{
		{
			name: "AliasKeyCert_BadSignatureVersion",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.SignatureVersion = 0xFFFFFFFF
			},
			wantErr: ErrAKCSignatureVersion,
		},
		{
			name: "AliasKeyCert_BadSignaturePurpose",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.SignaturePurpose = 0xFFFFFFFF
			},
			wantErr: ErrAKCSignaturePurpose,
		},
		{
			name: "AliasKeyCert_BadKeyType",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.KeyType = 0xF
			},
			wantErr: ErrAKCKeyType,
		},
		{
			name: "AliasKeyCert_BadKeyOp",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.KeyOp = 0xF
			},
			wantErr: ErrAKCKeyOp,
		},
		{
			name: "AliasKeyCert_BadKeyAlg",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.KeyAlg = 0xF
			},
			wantErr: ErrAKCKeyAlg,
		},
		{
			name: "AliasKeyCert_BadReserved0",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.Reserved0 = [2]byte{0xFF}
			},
			wantErr: ErrAKCReserved0,
		},
		{
			name: "AliasKeyCert_BadPubKeySize",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.PubKeySize = 0xFFFF
			},
			wantErr: ErrAKCPubKeySize,
		},
		{
			name: "AliasKeyCert_BadReserved1",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.Reserved1 = [8]byte{0xFF}
			},
			wantErr: ErrAKCReserved1,
		},
		{
			name: "AliasKeyCert_ExtensionHeaderTypeFWHash",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.FWHash = [32]byte{}

			},
			wantErr: ErrAKCExtensionHeaderType,
		},
		{
			name: "AliasKeyCert_ExtensionHeaderTypeNone",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.AliasKeyCertificate.Header.ExtensionHeaderType = 1
			},
			wantErr: ErrAKCExtensionHeaderType,
		},
		{
			name: "DeviceIdCert_HardwareId0",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.HWID = 0
			},
			wantErr: ErrDIDCHWID0,
		},
		{
			name: "DeviceIdCert_BadSignatureVersion",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.SignatureVersion = 0xFFFFFFFF
			},
			wantErr: ErrDIDCSignatureVersion,
		},
		{
			name: "DeviceIdCert_BadSignaturePurpose",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.SignaturePurpose = 0xFFFFFFFF
			},
			wantErr: ErrDIDCSignaturePurpose,
		},
		{
			name: "DeviceIdCert_BadKeyType",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.KeyType = 0xF
			},
			wantErr: ErrDIDCKeyType,
		},
		{
			name: "DeviceIdCert_BadKeyOp",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.KeyOp = 0xF
			},
			wantErr: ErrDIDCKeyOp,
		},
		{
			name: "DeviceIdCert_BadKeyAlg",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.KeyAlg = 0xF
			},
			wantErr: ErrDIDCKeyAlg,
		},
		{
			name: "DeviceIdCert_BadExtensionHeaderType",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.ExtensionHeaderType = 1
			},
			wantErr: ErrDIDCExtensionHeaderType,
		},
		{
			name: "DeviceIdCert_BadSignedDataSize",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.SignedDataSize = 0xFFFF
			},
			wantErr: ErrDIDCSignedDataSize,
		},
		{
			name: "DeviceIdCert_BadScribeKeyInfo",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Header.KeyInfo = [4]byte{0xFF}
			},
			wantErr: ErrDIDCScribeKeyInfo,
		},
		{
			name: "DeviceIdCert_BadSignature",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDCertificate.Signature.R = [32]byte{
					0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
					0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f}
			},
			wantErr: ErrDIDCSignature,
		},
		{
			name: "DeviceIdScribeCert_BadCertHash",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDScribeCertificate.DeviceIDCertHash = [32]byte{0xFF}
			},
			wantErr: ErrDIDSCCertHash,
		},
		{
			name: "DeviceIdScribeCert_BadScribeKey",
			certChainPerturbator: func(c *TitanDiceScribeCertificateChain) {
				c.DeviceIDScribeCertificate.ScribeRWKey = ECP256PublicKey{}
			},
			wantErr: ErrDIDSCScribeKey,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			tcInput := defaultFEKDICEScribeCertChain
			tc.certChainPerturbator(&tcInput)

			opts := defaultTestCaseOpts
			tcValidator, err := NewValidator(opts)
			if err != nil {
				t.Fatalf("NewValidator(%v) failed: %v", opts, err)
			}

			err = ValidateScribeCertificateChain(&tcInput, tcValidator)
			if !errors.Is(err, tc.wantErr) {
				t.Errorf("[%s] ValidateScribeCertificateChain(%v, %v) = %v, want %v", tc.name, tcInput, opts, err, tc.wantErr)
			}
		})
	}
}

func TestVerifyQualifiedName(t *testing.T) {
	for _, tc := range []struct {
		name                  string
		ekc                   EKCertificate
		expectedTemplate      *tpm2.TPMTPublic
		expectFirmwareLimited bool
		wantErr               error
	}{
		{
			name:                  "FEKTemplate_Success",
			ekc:                   defaultFEKCertificate,
			expectedTemplate:      titanFEKTemplate(),
			expectFirmwareLimited: true,
		},
		{
			name:                  "EKTemplate_Success",
			ekc:                   defaultEKCertificate,
			expectedTemplate:      titanEKTemplate(),
			expectFirmwareLimited: false,
		},
		{
			name:                  "FEKTemplate_Failure",
			ekc:                   defaultFEKCertificate,
			expectedTemplate:      titanFEKTemplate(),
			expectFirmwareLimited: true,
			wantErr:               ErrEKTemplate,
		},
		{
			name:                  "EKTemplate_Failure",
			ekc:                   defaultEKCertificate,
			expectedTemplate:      titanEKTemplate(),
			expectFirmwareLimited: false,
			wantErr:               ErrEKTemplate,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			ekPub := ECDSAPublicKey(tc.ekc.PublicKey)
			tc.expectedTemplate.Unique = pubKeyToECCPublicID(ekPub)

			if tc.wantErr != nil {
				// Modify a random bit in the EK certificate qualified name.
				r := rand.New(rand.NewSource(time.Now().UnixNano()))
				randomNumber := r.Intn(32)
				tc.ekc.Header.QualifiedName[randomNumber] = 0
			}

			if err := verifyEKQualifiedName(&tc.ekc, tc.expectedTemplate, tc.expectFirmwareLimited); !errors.Is(err, tc.wantErr) {
				t.Fatalf("[%s] verifyEKQualifiedName(%x, %v, %#v): got %v, want %v", tc.name, tc.ekc, tc.expectedTemplate, tc.expectFirmwareLimited, err, tc.wantErr)
			}
		})
	}
}

func TestValidateEKCertificateSuccess(t *testing.T) {
	for _, tc := range []struct {
		name                  string
		baseCert              EKCertificate
		certChain             TitanDiceScribeCertificateChain
		expectFirmwareLimited bool
	}{
		{
			name:                  "EKTemplate",
			baseCert:              defaultEKCertificate,
			certChain:             defaultEKDICEScribeCertChain,
			expectFirmwareLimited: false,
		},
		{
			name:                  "FEKTemplate",
			baseCert:              defaultFEKCertificate,
			certChain:             defaultFEKDICEScribeCertChain,
			expectFirmwareLimited: true,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ekc := tc.baseCert
			akc := tc.certChain
			_, err := ValidateEKCertificate(&ekc, &akc.AliasKeyCertificate, tc.expectFirmwareLimited)
			if err != nil {
				t.Fatalf("ValidateEKCertificate(%#v, %#v) failed: %v", ekc, akc, err)
			}
		})
	}
}

func TestValidateEKCertificate_General_Errors(t *testing.T) {
	type testCase struct {
		name          string
		ekPerturbator func(*EKCertificate)
		wantErr       error
	}

	testCases := []testCase{
		{
			name: "BadSignatureVersion",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.SignatureVersion = 0xFFFFFFFF
			},
			wantErr: ErrEKSignatureVersion,
		},
		{
			name: "BadSignaturePurpose",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.SignaturePurpose = 0xFFFFFFFF
			},
			wantErr: ErrEKSignaturePurpose,
		},
		{
			name: "BadKeyType",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.KeyType = 0xF
			},
			wantErr: ErrEKKeyType,
		},
		{
			name: "BadKeyOp",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.KeyOp = 0xF
			},
			wantErr: ErrEKKeyOp,
		},
		{
			name: "BadKeyAlg",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.KeyAlg = 0xFF
			},
			wantErr: ErrEKKeyAlg,
		},
		{
			name: "BadReserved0",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.Reserved0 = [2]byte{0xFF}
			},
			wantErr: ErrEKReserved0,
		},
		{
			name: "BadPubKeySize",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.PubKeySize = 0xFFFF
			},
			wantErr: ErrEKPubKeySize,
		},
		{
			name: "BadReserved1",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.Reserved1 = [8]byte{0xFF}
			},
			wantErr: ErrEKReserved1,
		},
		{
			name: "ExtensionHeaderTypeNone",
			ekPerturbator: func(c *EKCertificate) {
				c.Header.Header.ExtensionHeaderType = 0xFF
			},
			wantErr: ErrEKExtensionHeaderType,
		},
		{
			name: "BadSignature",
			ekPerturbator: func(c *EKCertificate) {
				c.Signature.R = [32]byte{
					0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
					0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f}
			},
			wantErr: ErrEKSignature,
		},
	}

	scenarios := []struct {
		template              string
		baseCert              EKCertificate
		certChain             TitanDiceScribeCertificateChain
		expectFirmwareLimited bool
	}{
		{
			template:              "EKTemplate",
			baseCert:              defaultEKCertificate,
			certChain:             defaultEKDICEScribeCertChain,
			expectFirmwareLimited: false,
		},
		{
			template:              "FEKTemplate",
			baseCert:              defaultFEKCertificate,
			certChain:             defaultFEKDICEScribeCertChain,
			expectFirmwareLimited: true,
		},
	}

	for _, scenario := range scenarios {
		t.Run(scenario.template, func(t *testing.T) {
			t.Parallel() // Run scenarios (EK vs FEK) in parallel

			for _, tc := range testCases {
				t.Run(tc.name, func(t *testing.T) {
					t.Parallel() // Run different perturbators in parallel

					input := scenario.baseCert
					tc.ekPerturbator(&input)

					_, err := ValidateEKCertificate(&input, &scenario.certChain.AliasKeyCertificate, scenario.expectFirmwareLimited)
					if !errors.Is(err, tc.wantErr) {
						t.Errorf("ValidateEKCertificate() err = %v, want %v", err, tc.wantErr)
					}
				})
			}
		})
	}
}

func TestValidateEKCertificate_FirmwareMajorVersion_Errors(t *testing.T) {
	for _, tc := range []struct {
		name                  string
		baseCert              EKCertificate
		certChain             TitanDiceScribeCertificateChain
		expectFirmwareLimited bool
		wantErr               error
	}{
		{
			name:                  "EKTemplate_BadFMV",
			baseCert:              defaultEKCertificate,
			certChain:             defaultEKDICEScribeCertChain,
			expectFirmwareLimited: true,
			wantErr:               ErrEKFirmwareMajorVersionMismatch,
		},
		{
			name:                  "FEKTemplate_BadFMV",
			baseCert:              defaultFEKCertificate,
			certChain:             defaultFEKDICEScribeCertChain,
			expectFirmwareLimited: false,
			wantErr:               ErrEKFirmwareMajorVersionNonZero,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ekc := tc.baseCert
			akc := tc.certChain
			_, err := ValidateEKCertificate(&ekc, &akc.AliasKeyCertificate, tc.expectFirmwareLimited)
			if !errors.Is(err, tc.wantErr) {
				t.Fatalf("ValidateEKCertificate(%#v, %#v): got %v, want %v", ekc, akc, err, tc.wantErr)
			}
		})
	}
}
