// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package titandice

// KeyInfo represents a Titan ECDSA key by the value `SHA256(x || y)[0:4]`
type KeyInfo [4]byte

// KeyID represents a Titan ECDSA key by the value `SHA256(x || y)[0:16]`
type KeyID [16]byte

type ValidateScribeCertificateChainOptions struct {
	// The set of trusted scribe certificates that signed the
	// DeviceIdScribeCertificate and the DeviceIdCertificate.
	ScribeCertificates [][]byte

	// The set of trusted RW code signing key infos.
	RwSigningKeyInfos []KeyInfo
}

// AliasKeyCertificateHeader represents the header of an AliasKeyCertificate attested over the Alias
// public key by the DeviceId key. The certificate is used as part of DICE based
// chained attestations in Titan chips.
type AliasKeyCertificateHeader struct {
	SignatureVersion    SignatureVersion
	SignaturePurpose    SignaturePurpose
	ExtensionHeaderType SigExtensionHeaderType
	KeyType             KeyType
	KeyOp               KeyOp
	KeyAlg              KeyAlg
	KeyInfo             KeyInfo
	CertValidity        [16]byte
	HWID                uint64
	HWCat               uint16
	Reserved0           [2]byte
	BootloaderTag       uint32
	FWEpoch             uint32
	FWMajorVersion      uint16
	PubKeySize          uint16
	Reserved1           [8]byte
}

// Elliptic Curve signature as per the NIST P256 standard. All fields are
// little-endian with a 32-bit word size. p256_from_le_bin can be used to get a
// usable pair of p256_ints.
type ECP256Signature struct {
	// The r parameter of the EC P256 signature.
	R [32]byte
	// The s parameter of the EC P256 signature.
	S [32]byte
}

// Elliptic Curve public key as per the NIST P256 standard. All fields are
// little-endian with a 32-bit word size. p256_from_le_bin can be used to get a
// usable pair of p256_ints.
type ECP256PublicKey struct {
	// The x coordinate of the EC P256 public key.
	QAX [32]byte
	// The y coordinate of the EC P256 public key.
	QAY [32]byte
}

// Represents an AliasKeyCertificate comprised of the header(metadata), the
// public part of the Alias key and a signature generated by the DeviceId key.
// The message is generated by the bootloader and transferred to the firmware.
// It will then be transmitted to the CAK certifying authority for validation of
// CAK CSRs which will contain a signature generated using the Alias key.
type AliasKeyCertificate struct {
	// Represents the header of an AliasKeyCertificate attested over the Alias
	// public key by the DeviceId key. The certificate is used as part of DICE based
	// chained attestations in Titan chips.
	Header AliasKeyCertificateHeader

	PublicKey ECP256PublicKey
	Signature ECP256Signature

	// A hash of the SignedHeader struct, representing the firmware measurement.
	//
	// Should only contain a value if the `ExtensionHeaderType` in the `Header`
	// field is `SigExtensionHeaderTypeFirmwareHash``.
	FWHash [32]byte
}

// Represents the header of a DeviceIdCertificate attested over the DeviceId
// public key by Scribe or the Titan Validation Authority (VA). The certificate
// is used as part of DICE based chained attestations in Titan
// chips.
type DeviceIDCertificateHeader struct {
	SignatureVersion    SignatureVersion
	SignaturePurpose    SignaturePurpose
	ExtensionHeaderType SigExtensionHeaderType
	KeyType             KeyType
	KeyOp               KeyOp
	KeyAlg              KeyAlg
	KeyInfo             KeyInfo
	CertValidity        [16]byte
	ScribeKeyID         KeyID
	HWID                uint64
	HWCat               uint16
	SignedDataSize      uint16
	BootloaderTag       uint32
}

// Represents a DeviceIdCertificate comprising of the header (metadata), the DeviceId
// public key and a signature generated by the Scribe or the Titan Validation
// Authority (VA). The message is generated and transmitted by Scribe to the chip
// where it is persisted and optionally, it is also generated by the VA from
// DeviceIdCertificateSigningRequest and stored in CertStore.
type DeviceIDCertificate struct {
	Header    DeviceIDCertificateHeader
	Key       ECP256PublicKey
	Signature ECP256Signature
}

// Represents a DeviceIdScribeCertificate comprising of the hash of the
// DeviceIdCertificate, the Scribe RW public key and a signature generated by
// the Scribe over DeviceIdCertificate using the Scribe's RW key.
type DeviceIDScribeCertificate struct {
	DeviceIDCertHash [32]byte
	ScribeRWKey      ECP256PublicKey
	Signature        ECP256Signature
}

// A certificate chain that is used to validate an EKSigningRequeste using an
// AliasKeyCertificate, DeviceIdCertificate and DeviceIdScribeCertificate.
type TitanDiceScribeCertificateChain struct {
	// Contains the Alias Key used to validate the EKSigningRequest.
	AliasKeyCertificate AliasKeyCertificate

	// Contains the Device ID public key used to validate the AliasKeyCertificate.
	DeviceIDCertificate DeviceIDCertificate

	// Contains a self signed certificate over the hash of the
	// DeviceIdCertificate.
	DeviceIDScribeCertificate DeviceIDScribeCertificate
}

// The header for a key certificate.
type KeycertSignatureHeader struct {
	SignatureVersion    SignatureVersion
	SignaturePurpose    SignaturePurpose
	ExtensionHeaderType SigExtensionHeaderType
	KeyType             KeyType
	KeyOp               KeyOp
	KeyAlg              KeyAlg
	KeyInfo             KeyInfo
	CertValidity        [16]byte
	HWID                uint64
	HWCat               uint16
	Reserved0           [2]byte
	BootloaderTag       uint32
	FWEpoch             uint32
	FWMajorVersion      uint16
	PubKeySize          uint16
	Reserved1           [8]byte
}

type EKCertificateHeader struct {
	// Common key certificate signature header.
	Header KeycertSignatureHeader

	// SHA256 Hash of the Read-Write firmware.
	RWHash [32]byte

	// SHA256 Qualified name of the object.
	QualifiedName [32]byte
}

// Represents an EndorsementKeyCertificate, which contains the public part
// of the EK. This certificate attests that the EK public key genuinely
// belongs to an authentic TPM produced by the specified manufacturer.
// The certificate is signed by an Alias Key.
type EKCertificate struct {
	Header EKCertificateHeader

	// EK public key.
	PublicKey ECP256PublicKey

	// Signature over header || public_key.
	Signature ECP256Signature
}
